export const TRAVEL_INTELLIGENCE_SOURCES = [
  {
    slug: "costa-rica",
    label: "Costa Rica",
    sources: [
      {
        id: "es-maec",
        audience: "ES",
        label: "España — Recomendaciones de viaje",
        url: "https://www.exteriores.gob.es/es/ServiciosAlCiudadano/Paginas/Detalle-recomendaciones-de-viaje.aspx?trc=Costa+Rica",
        trust: "official",
      },
      {
        id: "uk-fcdo",
        audience: "UK",
        label: "UK FCDO — Costa Rica travel advice",
        url: "https://www.gov.uk/foreign-travel-advice/costa-rica",
        trust: "official",
      },
      {
        id: "us-state",
        audience: "US",
        label: "US State Department — Costa Rica Travel Advisory",
        url: "https://travel.state.gov/en/international-travel/travel-advisories/costa-rica.html",
        trust: "official",
      },
      {
        id: "mopt",
        audience: "LOCAL",
        label: "Costa Rica MOPT",
        url: "https://www.mopt.go.cr/",
        trust: "official",
      },
      {
        id: "imn",
        audience: "LOCAL",
        label: "Instituto Meteorológico Nacional de Costa Rica",
        url: "https://www.imn.ac.cr/",
        trust: "official",
      },
      {
        id: "cne",
        audience: "LOCAL",
        label: "Comisión Nacional de Emergencias de Costa Rica",
        url: "https://www.cne.go.cr/",
        trust: "official",
      },
    ],
  },
  {
    slug: "sudafrica",
    label: "Sudáfrica",
    sources: [
      {
        id: "es-maec",
        audience: "ES",
        label: "España — Recomendaciones de viaje",
        url: "https://www.exteriores.gob.es/es/ServiciosAlCiudadano/Paginas/Detalle-recomendaciones-de-viaje.aspx?trc=Sud%C3%A1frica",
        trust: "official",
      },
      {
        id: "uk-fcdo",
        audience: "UK",
        label: "UK FCDO — South Africa travel advice",
        url: "https://www.gov.uk/foreign-travel-advice/south-africa",
        trust: "official",
      },
      {
        id: "us-state",
        audience: "US",
        label: "US State Department — South Africa",
        url: "https://travel.state.gov/en/international-travel/travel-advisories/south-africa.html",
        trust: "official",
      },
      {
        id: "gov-sa",
        audience: "LOCAL",
        label: "South African Government",
        url: "https://www.gov.za/",
        trust: "official",
      },
    ],
  },
  {
    slug: "jordania",
    label: "Jordania",
    sources: [
      {
        id: "es-maec",
        audience: "ES",
        label: "España — Recomendaciones de viaje",
        url: "https://exteriores.gob.es/Embajadas/amman/en/ViajarA/Paginas/Recomendaciones-de-viaje.aspx",
        trust: "official",
      },
      {
        id: "uk-fcdo",
        audience: "UK",
        label: "UK FCDO — Jordan travel advice",
        url: "https://www.gov.uk/foreign-travel-advice/jordan",
        trust: "official",
      },
      {
        id: "us-state",
        audience: "US",
        label: "US State Department — Jordan",
        url: "https://travel.state.gov/en/international-travel/travel-advisories/jordan.html",
        trust: "official",
      },
    ],
  },
  {
    slug: "grecia",
    label: "Grecia",
    sources: [
      {
        id: "es-maec",
        audience: "ES",
        label: "España — Recomendaciones de viaje",
        url: "https://www.exteriores.gob.es/es/ServiciosAlCiudadano/Paginas/Detalle-recomendaciones-de-viaje.aspx?trc=Grecia",
        trust: "official",
      },
      {
        id: "uk-fcdo",
        audience: "UK",
        label: "UK FCDO — Greece travel advice",
        url: "https://www.gov.uk/foreign-travel-advice/greece",
        trust: "official",
      },
      {
        id: "us-state",
        audience: "US",
        label: "US State Department — Greece",
        url: "https://travel.state.gov/en/international-travel/travel-advisories/greece.html",
        trust: "official",
      },
    ],
  },
];

export const SUPPORTED_MARKETS = [
  { code: "ES", label: "España", language: "es" },
  { code: "MX", label: "México", language: "es" },
  { code: "AR", label: "Argentina", language: "es" },
  { code: "CO", label: "Colombia", language: "es" },
  { code: "CL", label: "Chile", language: "es" },
  { code: "PE", label: "Perú", language: "es" },
  { code: "BR", label: "Brasil", language: "pt" },
  { code: "US", label: "Estados Unidos", language: "en" },
  { code: "UK", label: "Reino Unido", language: "en" },
  { code: "CA", label: "Canadá", language: "en" },
  { code: "AU", label: "Australia", language: "en" },
  { code: "DE", label: "Alemania", language: "de" },
  { code: "FR", label: "Francia", language: "fr" },
  { code: "IT", label: "Italia", language: "it" },
  { code: "NL", label: "Países Bajos", language: "nl" },
  { code: "PT", label: "Portugal", language: "pt" },
];
